name: 🤔 Question
description: Submit a question
labels: ["question"]

body:
  - type: markdown
    attributes:
      value: |
        ***Your question here***

  - type: textarea
    id: description
    attributes:
      label: Write your question
      description: |
        *Write your question. Attach screenshots if needed.*
    validations:
      required: true